### ISSUE TITLE
download issue

### ISSUE THREAD

**Issue by AbhinanduReddy** [rwightman/udacity-driving-reader#22]
iam using window 10 home which is not compatable for installing docker ,suggest any alternative

**Comment by rwightman** [comment]
@AbhinanduReddy it maybe be possible to get docker in Windows, possibly with WSL (or WSL 2 when it's out) in Windows... not sure on the specifics, but a number of articles can be found, things are changing in that area 

If you can get ROS 1 installed in Windows, you can just use the scripts this repository without the docker container. Otherwise, you'll need Linux.
